controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
    
api_login_check:
    path: /api/login_check

user_api_create:
   path: /api/users
   controller: 'App\Controller\UserController::create'
   methods: ['POST']

blog_api_create:
   path: /api/blogs
   controller: 'App\Controller\BlogController::create'
   methods: ['POST']

blog_api_index:
   path: /api/blogs
   controller: 'App\Controller\BlogController::index'
   methods: ['GET']


blog_api_show:
   path: /api/blogs/{id}
   controller: 'App\Controller\BlogController::show'
   methods: ['GET']

blog_api_update:
   path: /api/blogs/{id}
   controller: 'App\Controller\BlogController::update'
   methods: ['PUT']


blog_api_delete:
   path: /api/blogs/{id}
   controller: 'App\Controller\BlogController::delete'
   methods: ['DELETE']


blog_api_search_by_id:
   path: /api/blogs/search/{id}
   controller: 'App\Controller\BlogController::findById'
   methods: ['GET']
